### ISSUE TITLE
PID variables in EEPROM

### ISSUE THREAD

**Issue by neelfirst** [RespiraWorks/VentilatorSoftware#15] opened 2020-04-02 03:37 UTC
Copied thread from inceptionev/FixMoreLungs

@rwilbur We will need the variables to be stored in EEPROM so that in case of a reboot we still have the correct values for the variables

@lee-matthews Indeed, this functionality shall be provided by the eeprom module in the software.

**Comment by martukas** [comment] 2020-04-13 03:33
Is this deserving to be in alpha? This is a safety feature in case of reboot, but is it crucial for functioning prototype? Same applies to #56 and #58

**Comment by lee-matthews** [comment] 2020-04-16 12:10
I think we can move this to beta. We can just store these values as constants in flash for the time being.

**Comment by jlebar** [comment] 2020-04-25 00:44
Dupe of https://github.com/RespiraWorks/VentilatorSoftware/issues/56

**Closed by jlebar** 2020-04-25 00:44 UTC
Labels: Controller
