### ISSUE TITLE
Calculate instantaneous patient volume and transmit to GUI computer

### ISSUE THREAD

**Issue by lee-matthews** [RespiraWorks/VentilatorSoftware#101] opened 2020-04-16 13:35 UTC
Read flow, pressure and zone information from the respiration cycle state machine, add timestamp and transmit to GUI interface machine.

**Comment by jlebar** [comment] 2020-04-23 16:16
This is a matter of fixing in the following TODO: https://github.com/RespiraWorks/VentilatorSoftware/blob/fa15b89/controller/src/pid.cpp#L126

The issue is I'm not sure what to put in there.  I'm planning to go to Oakland this weekend to touch the physical device.

**Comment by jlebar** [comment] 2020-04-25 18:36
This issue is not yet closed per: https://github.com/RespiraWorks/VentilatorSoftware/pull/160#issuecomment-618938322

**Comment by jlebar** [comment] 2020-04-26 02:39
Renaming based on what's left to do here.  Volume isn't needed for alpha.

**Comment by jkff** [comment] 2020-04-29 19:58
This is a dupe of other bugs related to calculating TV.

**Closed by jkff** 2020-04-29 19:58 UTC
Labels: Controller
