### ISSUE TITLE
Calibration data storage 

### ISSUE THREAD

**Issue by lee-matthews** [RespiraWorks/VentilatorSoftware#97] opened 2020-04-16 12:34 UTC
Write code to store calibration data in a non-volatile fashion (eeprom)
- This calibration data shall be able to be set from the GUI
- Add some checksum to be sure that this hasn't been corrupted in storage
Write code to read the calibration data from non-volatile memory
- Make the calibration data available to the mcu's sensors
- Check that the data hasn't been corrupted using the checksum

This will include calibration data for the pressure and flow sensors

**Comment by jkff** [comment] 2020-04-29 19:59
This is a duplicate of #170

**Closed by jkff** 2020-04-29 19:59 UTC
Labels: Controller
